apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: workflowpubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: "ServiceBus:ConnectionString"
      key:  "ServiceBus:ConnectionString"
auth:
  secretStore: daprshowcasesecretstore